### ISSUE TITLE
Disks stats not available

### ISSUE THREAD

**Issue by Oneel77** [wozniakpawel/synology-grafana-prometheus-overly-comprehensive-dashboard#13]
Hi,
I've followed all the instructions, but I'm only seeing storage utilization, and not the stats for Disk Read and Write (no data or Data is missing a number field is displayed) .
Any suggestions?
Thanks!

**Comment by rootakaunt** [comment]
I have a similar issue. The entire Storage and Network sections show No Data. From the System Info section 80% of the data is also missing. Any ideas please?

**Comment by mikepaxton** [comment]
> I have a similar issue. The entire Storage section shows No Data. Any ideas please?

Try editing the one of the panels like disk Read (Rate) and change the job to job="node" rather than nodeexporter.  That worked for me. 

Orignial: irate(node_disk_written_bytes_total{job="nodeexporter"}[$__rate_interval])
Modified: irate(node_disk_read_bytes_total{job="node"}[$__rate_interval])

<img width="591" alt="Image" src="https://github.com/user-attachments/assets/51d0c6cb-a495-4b10-bb60-25e33125898b" />

**Comment by rootakaunt** [comment]
Thank you for your suggestion but it didn't work for me. It only changed the message from "Data is missing a number field" to "No Data".

**Comment by mikepaxton** [comment]
> Thank you for your suggestion but it didn't work for me. It only changed the message from "Data is missing a number field" to "No Data".

Under the Query option inside Prometheus, what output do you get when you query for the "node_disk_written_bytes_total"?

Are you running both node-exporter and cadvisor on the machine you are trying to gather metrics from?

**Comment by rootakaunt** [comment]
I am running both node-exporter and cadvisor as docker images inside Container Manager on my NAS. 

I am having trouble accessing the Prom GUI. If I type in IP_ADDR:9090 in my browser it won't connect. I see inside the YAML file Prom is installed under the hostname http://prometheus:9090 but that hostname is only accessible within the containers, not my laptop. When I figure out how to access the Prom GUI I will let you know the outcome of the command. Thanks again!

**Comment by mikepaxton** [comment]
Not being able to connect to the container from your laptop suggests a networking issue.

By default, containers communicate via a Docker bridge network. To make Prometheus accessible from your laptop, you need to bind it to the host network or ensure proper port mapping.  
Any firewalls running that could block access?

Here is my yaml file for Prom.  Maybe it will help you track the issue down.
I'm running this container as an LXC in Proxmox.


```
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--storage.tsdb.retention.time=60d'
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - /home/admin/source/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  prometheus_data:

networks:
  monitoring:
    name: monitoring
    external: true
```


Regarding the "monitoring" network.  I set it up that way because I've got a bunch of other metrics gathering services running inside that container and I wanted to keep them separated from non metric services.


With regards to cadvisor and node-exporter, i'm running them on my Synology NAS.

Node-Exporter

```
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    privileged: true  
    read_only: true
    user: 1028:101
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
      - --path.udev.data=/host/run/udev/data
      #- --collector.diskstats.device-exclude=""      
      #- --collector.disable-defaults
      - --collector.stat
      - --collector.time
      - --collector.cpu
      - --collector.loadavg
      - --collector.hwmon
      - --collector.meminfo
      - --collector.diskstats
      - --collector.systemd
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    network_mode: host
    restart: unless-stopped
```

Cadvisor:

```
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
      - '--docker_only=true'
    container_name: cadvisor
    hostname: cadvisor
    read_only: true
    user: 0:0
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
```

I don't recall why I'm running Cadvisor with the UID and GUID as 0:0.  I didn't make notes on it, must have been the only way I got it to work.  It obviously must have needed root for some reason.  I should probably go back and figure that one out, I don't like it running as root.

**Comment by rootakaunt** [comment]
You were correct! The playbook did not expose the Docker ports to the outside. I fixed that and now I can access Prom. Thank you for that!

Back to your previous post, when I run the query `node_disk_written_bytes_total` inside Prom, I get this response:

node_disk_written_bytes_total{device="dm-0", instance="nodeexporter:9100", job="nodeexporter"}	96549765120
node_disk_written_bytes_total{device="dm-1", instance="nodeexporter:9100", job="nodeexporter"}	96549765120
node_disk_written_bytes_total{device="md0", instance="nodeexporter:9100", job="nodeexporter"}	2159595520
node_disk_written_bytes_total{device="md1", instance="nodeexporter:9100", job="nodeexporter"}	8192
node_disk_written_bytes_total{device="md2", instance="nodeexporter:9100", job="nodeexporter"}	96549765120
node_disk_written_bytes_total{device="sda", instance="nodeexporter:9100", job="nodeexporter"}	47673973760
node_disk_written_bytes_total{device="sdb", instance="nodeexporter:9100", job="nodeexporter"}	47150697472
node_disk_written_bytes_total{device="sdc", instance="nodeexporter:9100", job="nodeexporter"}	51380415488
node_disk_written_bytes_total{device="sdd", instance="nodeexporter:9100", job="nodeexporter"}	52141837312
node_disk_written_bytes_total{device="synoboot", instance="nodeexporter:9100", job="nodeexporter"}	4096
node_disk_written_bytes_total{device="synoboot1", instance="nodeexporter:9100", job="nodeexporter"}	0
node_disk_written_bytes_total{device="synoboot2", instance="nodeexporter:9100", job="nodeexporter"}	4096

**Comment by mikepaxton** [comment]
Sorry for the delay in gettin back to you, got a bit sidetracked on another project.

I just went back and compared my dashboard to that of the one provided here as a .json file.  I noticed I made a number of changes to get it to work correctly for my setup.  I also noticed in my notes on this Grafana/Prometheus project, another issue listed under this repo, noted the same issue regarding missing disk drive data, issue #5.  You might check that out.  

I'll try to list the changes I made in order to get this dashboard to work.  Keep in mind, I have two Synology servers, so I made some of these changes in order to get the dashboard to work for my environment.  But, this all should work for you, regardless of number of servers.

First, inside the prometheus.yml config file I mapped the target IP to a server name:

```
# Synology Servers
  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.0.10:9100']
        labels:
          instance: 'Olympus'
      - targets: ['10.0.0.16:9100']
        labels:
          instance: 'Rainier'
```
This is a copy of the same query you ran above on mine.

```
node_disk_written_bytes_total{device="sata1", instance="Olympus", job="node"}
``
Note: my job="node" is just how I named the job in my config.  I've modified the below info to reflect your job name of "nodeexporter".

In the dashboard I added a variable to the dashboard settings.  In the upper right corner, click Edit and then settings.  Click on the Variables tab and add a new Variable.

Set the variable type as a "Query" with the name being "node" and the label being "Host".  Under Show on dashboard choose Label and value.  Choose your data source.  Under the Query section, make the query type =" Label value". Label = "instance".  Node = "node_uname_info".   Sort it alphabetically (asc), this is only needed for multiple servers.  Make sure refresh = "On dashboard load".  That should do it here.  Click Save dashboard in the upper right corner.

You should now see two drop down menus at the top of the dashboard.  One is Datasource and the other is Host.  For me, the Datasource is Prometheus as that's the name I gave it inside of Grafana.  My Host is either of my two server names.

Back at the Dashboard, scroll down to the Storage area and click on the  (⋮) menu for Disk Read Total and choose edit.  In the Metrics Query use the following:  

```
irate(node_disk_read_bytes_total{job="nodeexporter", instance="$node"}[$__rate_interval])
```

In the Transformations Tab click on each of disks you want to monitor.  For me, they are my Sata disks, labeled Sata1, Sata2, etc.  Click the Save dashboard in up right corner and see if the data is now correctly showing inside the Disk Read Total widget.  If it does, then make those changes to the rest of the storage widgets.

Let me know the outcome of these changes.
